/**
 * @fileoverview gRPC-Web generated client stub for lepton
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.1
// 	protoc              v6.32.0
// source: login.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as login_pb from './login_pb'; // proto import: "login.proto"


export class LoginServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCheckPassword = new grpcWeb.MethodDescriptor(
    '/lepton.LoginService/CheckPassword',
    grpcWeb.MethodType.UNARY,
    login_pb.CheckPasswordRequest,
    login_pb.CheckPasswordReply,
    (request: login_pb.CheckPasswordRequest) => {
      return request.serializeBinary();
    },
    login_pb.CheckPasswordReply.deserializeBinary
  );

  checkPassword(
    request: login_pb.CheckPasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<login_pb.CheckPasswordReply>;

  checkPassword(
    request: login_pb.CheckPasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: login_pb.CheckPasswordReply) => void): grpcWeb.ClientReadableStream<login_pb.CheckPasswordReply>;

  checkPassword(
    request: login_pb.CheckPasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: login_pb.CheckPasswordReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lepton.LoginService/CheckPassword',
        request,
        metadata || {},
        this.methodDescriptorCheckPassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lepton.LoginService/CheckPassword',
    request,
    metadata || {},
    this.methodDescriptorCheckPassword);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/lepton.LoginService/Login',
    grpcWeb.MethodType.UNARY,
    login_pb.LoginRequest,
    login_pb.LoginReply,
    (request: login_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    login_pb.LoginReply.deserializeBinary
  );

  login(
    request: login_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<login_pb.LoginReply>;

  login(
    request: login_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: login_pb.LoginReply) => void): grpcWeb.ClientReadableStream<login_pb.LoginReply>;

  login(
    request: login_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: login_pb.LoginReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lepton.LoginService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lepton.LoginService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorLogout = new grpcWeb.MethodDescriptor(
    '/lepton.LoginService/Logout',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  logout(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  logout(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  logout(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/lepton.LoginService/Logout',
        request,
        metadata || {},
        this.methodDescriptorLogout,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/lepton.LoginService/Logout',
    request,
    metadata || {},
    this.methodDescriptorLogout);
  }

}

